---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ologami-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ologami-backend
  template:
    metadata:
      labels:
        app: ologami-backend
    spec:
      containers:
      - name: ologami-backend
        image: ologami-backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: ologami-backend-service
spec:
  selector:
    app: ologami-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
