---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ologami-be
  namespace: ologami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ologami-be
  template:
    metadata:
      labels:
        app: ologami-be
    spec:
      initContainers:
      - name: init-mongo
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z ologami-mongodb 27017; do echo waiting for mongo; sleep 2; done;']
      containers:
      - name: ologami-be
        image: ologami-be:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.1"
            memory: "0.5Gi"
        envFrom:
        - secretRef:
            name: ologami-be-env-secret
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - nc -z ologami-mongodb 27017
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ologami-be
  namespace: ologami
spec:
  selector:
    app: ologami-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
