apiVersion: apps/v1
kind: Deployment
metadata:
  name: ologami-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ologami
  template:
    metadata:
      labels:
        app: ologami
    spec:
      initContainers:
      - name: init-mongo
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup mongodb-service; do echo waiting for mongo; sleep 2; done;']
      containers:
      - name: ologami
        image: ologami:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "nslookup mongodb-service"
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ologami-service
spec:
  selector:
    app: ologami
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
