---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ologami-backend
  namespace: ologami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ologami-backend
  template:
    metadata:
      labels:
        app: ologami-backend
    spec:
      initContainers:
      - name: init-mongo
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup mongodb; do echo waiting for mongo; sleep 2; done;']
      containers:
      - name: ologami-backend
        image: ologami-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "0.5Gi"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "nslookup mongodb"
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ologami-backend
  namespace: ologami
spec:
  selector:
    app: ologami-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
